spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 32769
      database: local
      authentication-database: admin
      username: root
      password: root

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 32769
      database: local

---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 32769
      database: local